@api = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsInBlcm1pc28iOiJyZXN0YXVyYW50IiwiaWF0IjoxNjg1NTgxMzcwLCJleHAiOjE2ODYxODYxNzB9.Pfbfj209VjPsVKWEmb0QTP0j51YqLQI9Wnv94_P_yJI

GET {{api}}/restaurants
###
GET {{api}}/restaurant/2
x-access-token: {{token}}
###
GET {{api}}/restaurants/user/
x-access-token: {{token}}
###

POST {{api}}/restaurant
content-type:application/json
x-access-token: {{token}}

{
    "name": "restaurante1"
}
###
DELETE {{api}}/restaurant/63
x-access-token: {{token}}

###
PATCH  {{api}}/restaurant/81
content-type:application/json
x-access-token: {{token}}

{
    "name": "PRUEBA"
}
 