@api = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTY4MzM5ODc2NiwiZXhwIjoxNjgzNDg1MTY2fQ.kY_fFtNdoVywXzlAHEcYWuNy__L09r5oJ_6sdpKoSpU
GET {{api}}/usuarios
x-access-token: {{token}}
###
GET {{api}}/usuarios/email/a20170093@utem.edu.mx
x-access-token: {{token}}

###
//validar email
GET {{api}}/usuario/1
x-access-token: {{token}}
###
POST {{api}}/usuarios
content-type:application/json

{
    "nombre": "josuemagico",
    "apellidos":"morfin",
    "password":"123456",
    "email":"a20170093@utem.edu.mx"
}
###
DELETE {{api}}/usuarios/15
x-access-token: {{token}}
###
PATCH  {{api}}/usuarios/1
content-type: application/json
x-access-token: {{token}}
{
    "nombre": "josuemagico3",
    "apellidos": "morfin3"
}

